### ISSUE TITLE
How to get permissions for Google Cloud Storage buckets?

### ISSUE THREAD

**Issue by hammer** [opentargets/platform-input-support#12]
I don't seem to be able to access data in Google Cloud Storage buckets required for this project. For example, https://console.cloud.google.com/storage/browser/otar007-cosmic says
> Additional permissions required to list objects in this bucket: Ask a project or bucket owner to grant you 'storage.buckets.list'permissions (e.g., by giving your account the IAM Storage Object Viewer role).

**Comment by hammer** [comment]
H  7mob.

**Comment by hammer** [comment]
@deniseOme is there some mechanism by which I can request access to the Google Storage buckets used in this repo? We're blocked on access to this data right now.

**Comment by deniseOme** [comment]
@hammer, as I understand it you would like to run the platform input script in order to generate all data and run the pipeline.

You should run the pipeline instead. The instructions for that can be found in our help docs in our [How can I spin my own instance of the Platform?](https://docs.targetvalidation.org/faq/spin-your-own-instance) FAQ.

Please get back to us via our support email ie.e. support at targetvalidation dot org

**Comment by hammer** [comment]
@deniseOme thanks for the response! The instructions you link show how to load the ElasticSearch data from a snapshot; I care about provenance of data, so I'd like to build the ElasticSearch data precisely as the Open Targets Platform team does it. I'd also like to contribute to making the pipeline faster, more modular, more robust, and easier to reproduce.

More generally, if it's not possible for others to run the script in this repo, why have y'all made it open source?

I will send this same message via your support email but will copy our correspondence in this public forum so that others may learn from our discussion.

**Comment by d0choa** [comment]
@hammer thanks for the interest. The reason why you're not able to access that bucket is that it's part of our instance of the Open Targets Platform. We are aware of multiple private instances of the platform that didn't need access that bucket, in order to run the data pipeline or create their own instances. In particular, you should be able to access the aforementioned COSMIC data on the path described in the [config file](https://storage.googleapis.com/open-targets-data-releases/19.04/input/mrtarget.data.19.04.5.yml). Please let us know if this problem persists.

We will appreciate all help, particularly on the areas that you mentioned: modularity, robustness and reproducibility. The OT platform grew organically from the work of multiple people in the last 5 years with all the advantages and disadvantages derived from that. Also, you will have to understand that we have limited resources in terms of support. We have been trying to improve and centralise our documentation to facilitate the job to external developers but we acknowledge this is still far from perfect. Some documents that you might find useful can be found here:

- [Brief infrastructure description](https://docs.targetvalidation.org/technical-pipeline/infrastructure)
- [Technical release notes](https://docs.targetvalidation.org/technical-pipeline/technical-notes)
- [Adding private data](https://docs.targetvalidation.org/faq/add-your-own-data)
- [Blog about external instances of the OT platform](http://blog.opentargets.org/author/glennproctor/)
